spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hospitalmanagementtestdb

---

spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hospitalmanagementproddb